### ISSUE TITLE
Allow user inputs to select patches! 

### ISSUE THREAD

**Issue by Lucky-069** [decipher3114/Revancify#1]
Rather than selecting all patches by default. It would be nice to have an option to allow users to select which patches they want to use!

**Comment by decipher3114** [comment]
This is useless. Revanced has a settings page. So, it is on user to turn on or off the respective settings.
Also, I explicitly excluded Always autorepeat and custom speed bcz they are totally unsuable.
Making people select the patches will take away the simplicity and quickness from this project.
For full usage, Revanced builder is there.
My tool is for fast, simple and easy use.
Run, Press 1 or 2, TADA you have Revanced.

**Comment by Lucky-069** [comment]
Haha finally this got accepted! And you did add options lol so it isn't really useless
