### ISSUE TITLE
App isn't even opening in rooted latest version 17.34.35

### ISSUE THREAD

**Issue by tahmid8464** [decipher3114/Revancify#10]

**Comment by decipher3114** [comment]
The version you are using is not stable. Revanced dont support beta builds.
Leave Youtube beta program and use stable build.
![image](https://user-images.githubusercontent.com/84389932/188259085-6584db23-5a52-4a34-a144-e84a1b75aade.png)

**Comment by tahmid8464** [comment]
Got it. Anyways v17.34.35 has been released as stable today
