### ISSUE TITLE
Alternative to Termux Monet

### ISSUE THREAD

**Issue by szbinks** [decipher3114/Revancify#101]
In the readme there is this line :
Termux Monet (strictly recommended)

Problem : Link to Termux Monet is dead and this project seems dead.

So my questions are : "Is it a good idea to use Termux instead ? What are the possible consequences to do so ? Is there a better alternative ?

**Comment by 1node0001** [comment]
> In the readme there is this line : Termux Monet (strictly recommended)
> 
> Problem : Link to Termux Monet is dead and this project seems dead.
> 
> So my questions are : "Is it a good idea to use Termux instead ? What are the possible consequences to do so ? Is there a better alternative ?

Well regular Termux hasn't received an update for months now, it's even more behind than Monet. But I'm using regular Termux and it's working flawlessly. You do get Parsin error every now and then after patching is done and you try to install the patched apk. Just repatch and use 'pkg upgrade' command in Termux to update everything and you should be good to go.
