### ISSUE TITLE
Revancify does not work with the pacman bootstrap

### ISSUE THREAD

**Issue by EnderNon** [decipher3114/Revancify#105]
By installing the pacman bootstrap the program has an error, but the message gets overwritten by the fancy gui. You cannot install revancify before the pacman bootstrap because the bootstrap completely replaces the /data/data/com.termux/files/usr/ directory. Not sure what to do, as I'm fairly certain the error is due to being unable to fetch dependencies.

https://github.com/user-attachments/assets/c8f3c389-f9b6-4960-a1d7-efb675264766

See this video

**Comment by EnderNon** [comment]
![ezgif-frame-033](https://github.com/user-attachments/assets/5cd18107-4a5b-40b9-872c-8b8db021832d)
here's the frame where the error occurs

**Comment by LovecraftianGodsKiller** [comment]
Is this being worked on or...

Cuz I so badly want to use revanced but it not working with the pacman bootstrap is what it keeping me from using revancify.

**Comment by EnderNon** [comment]
no one knows. Last time I asked a few weeks prior to this issue, decipher closed it for an absurd reason imo. Check the history, it's in there somewhere.

**Comment by decipher3114** [comment]
2 options:

1. Manually install all dependencies and never let pkg to trigger.

2. PR with a satisfactory implementation of pacman.

**Comment by EnderNon** [comment]
> 2 options:
> 
> 1. Manually install all dependencies and never let pkg to trigger.
> 2. PR with a satisfactory implementation of pacman.

1 would just confuse the non advanced users too much. I vote 2, so you detect whether using pacman or apt, then make it do it specific to package manager.

**Comment by decipher3114** [comment]
Why do you expect non-advanced users to use pacman bootstrap instead of apt one?

1 seems to be the most appropriate one at this moment.

And if you vote 2, then a well implemented Pull Request is welcome.

**Comment by EnderNon** [comment]
> Why do you expect non-advanced users to use pacman bootstrap instead of apt one?
> 
> 1 seems to be the most appropriate one at this moment.
> 
> And if you vote 2, then a well implemented Pull Request is welcome.

My point is that if you told people how to install dependencies manually beforehand, people may be confused between the apt and pacman dependencies. Though now that I think about it, it likely isn't an issue if it's done like this:

- Remove automatic dependency installation from Revancify code
- Write in the README how to install required dependencies first, something like this:
  - Installing Dependencies
    - Note: if you are not sure or don't know, select the apt option.
    - For `apt` users: run this command:
      - `apt install package1 package2 package3 package4`
    - For `pacman` users run this command:
      - `pacman -S package1 package2 package3 package4`

Thus, users install dependencies manually instead of automatic, which will make it work but requires one more command run. So option 1

**Comment by decipher3114** [comment]
Better thing to do it to provide a command for pacman users and let Revancify handle it with apt.

If Revancify detects all dependencies pre-installed, it won't invoke apt.

**Comment by EnderNon** [comment]
I didn't know it does that, since I didn't know what dependencies were required. Can you provide a list?

**Comment by decipher3114** [comment]
I'll add the section in the README soon.

**Comment by someone5678** [comment]
> Better thing to do it to provide a command for pacman users and let Revancify handle it with apt.
> 
> If Revancify detects all dependencies pre-installed, it won't invoke apt.

Using termux's `pkg` command, we can apply auto install both for apt and pacman.

Ref:
https://github.com/someone5678/Revancify/commit/57f504df2d0b05ea388606c233c952a3dce532f9

Downside of above ref is that we can't "refresh" configuration (--conf-new) until we detect package manager and dealing individually...

**Comment by decipher3114** [comment]
This one seems to be a better solution. Configuration changes should be ignored by newbies and for techies, they know how to handle it.

Make a PR with a proper commit name and I'll merge it. Just make sure it works perfectly for everyone.

**Comment by decipher3114** [comment]
Fixed in #135
