### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by MrCeez** [decipher3114/Revancify#107]
Can't install due to an openjdk dependency error.

**Comment by MrCeez** [comment]
Error: Unable to locate package openjdk-17
![Screenshot_20241016_065523_Termux](https://github.com/user-attachments/assets/228f38f0-2eef-4111-94ee-38affdde24f1)

**Comment by auggie246** [comment]
> Error: Unable to locate package openjdk-17 ![Screenshot_20241016_065523_Termux](https://private-user-images.githubusercontent.com/16075377/376908923-228f38f0-2eef-4111-94ee-38affdde24f1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODM1ODMsIm5iZiI6MTczMDE4MzI4MywicGF0aCI6Ii8xNjA3NTM3Ny8zNzY5MDg5MjMtMjI4ZjM4ZjAtMmVlZi00MTExLTk0ZWUtMzhhZmZkZGUyNGYxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA2MjgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2Njg1NGNiZjBmOTc3MzY1OGViYzQ4MWM1YTRmMGVlNWRkMjYyMTIzODE1ZTUyODRmYWE3ODg5YmJkNWQ0YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DvMAoBHOvT9iJmq8Yoe_ibrQmeel1slKrl0Ho1qyWbI)

It's not working when using Termux from Play store. I got it working by switching to Termux from F-droid (redirected from the official github)
Probably some changes to termux in the playstore version as even `termux-change-repo` is no longer a valid command

**Comment by MrCeez** [comment]
Thank you
