### ISSUE TITLE
Started failing to patch after updating YouTube

### ISSUE THREAD

**Issue by ignhades** [decipher3114/Revancify#11]
bad 'com.google.android.youtube.apk': No such file or directory                                 
chmod: : No such file or directory
Mount failed...
![Screenshot_20220903-115514](https://user-images.githubusercontent.com/112747393/188258898-35da43d0-344f-480e-8f31-839ce1bdbc97.jpg)
![Screenshot_20220903-120221](https://user-images.githubusercontent.com/112747393/188258935-5d1626a3-5577-4717-9988-46a7325bb672.jpg)

**Comment by decipher3114** [comment]
You are using Beta build. Use stable builds only
also type this command

`ls ~/storage/Revancify`

and send screenshot please
![image](https://user-images.githubusercontent.com/84389932/188259168-aa4d0e04-9223-4abd-94b2-ed3991df7219.png)

**Comment by ignhades** [comment]
![Screenshot_20220903-121631](https://user-images.githubusercontent.com/112747393/188259291-cfc1993d-94dc-4df2-a8f1-a640a28a7406.jpg)

**Comment by decipher3114** [comment]
bro apps dont have .apk extension. It wont work

**Comment by decipher3114** [comment]
uninstall this tool and install again.

**Comment by ignhades** [comment]
Reinstalling the tool as well as downgrading the YouTube app to an earlier version did work. However I wasn't in the beta program which means it was pushed to me as a stable build, weird it didn't work for it that way. It's also listed as stable now in Apkmirror. Guessing I'll stay on the earlier version for the time being. Anyways thanks for the swift response. You may close the thread.

**Comment by decipher3114** [comment]
Thanks for appreciation. 👍
