### ISSUE TITLE
Getting this when trying to run revancify 2.0

### ISSUE THREAD

**Issue by Hazem42** [decipher3114/Revancify#119]
cp: cannot stat 'Revancify/revancify': No such file or directory
Revancify v2.0 is now available.
Run 'revancify -h' for help.

**Comment by Hazem42** [comment]
Fixed it. The command revancify tries to run _Revancify/revancify_, but the directory that gets installed with the curl command is called _decipher3114-Revancify-ddfa66e_, renaming the directory fixes the issue.

**Comment by decipher3114** [comment]
These types of errors might be frequent due to continuous changes in Revancify. I am trying to find the sweet spot for speed and compatiblity. It would be better if you join the Telegram support group.
