### ISSUE TITLE
Not able to build the Revanced app. 

### ISSUE THREAD

**Issue by StarDragonEmperor** [decipher3114/Revancify#12]
Hope this will help u to assist me.
![StitchIt_20220309010533_313](https://user-images.githubusercontent.com/96568306/188261135-0864816b-5c96-421b-a87c-8d77bf034780.png)

**Comment by decipher3114** [comment]
enter command
`ls ~/storage/Revancify"

and send screenshot

**Comment by StarDragonEmperor** [comment]
> enter command `ls ~/storage/Revancify`
> 
> and send screenshot

ok, will send

**Comment by StarDragonEmperor** [comment]
> enter command `ls ~/storage/Revancify`
> 
> and send screenshot

![Screenshot_20220905-103810_Termux](https://user-images.githubusercontent.com/96568306/188364711-63b0847d-1f46-459f-9c47-bca2df84e247.jpg)

**Comment by StarDragonEmperor** [comment]
> enter command `ls ~/storage/Revancify`
> 
> and send screenshot

![20220905_103952](https://user-images.githubusercontent.com/96568306/188364842-dacf49c8-de76-4170-b3fb-0e0905e27c65.jpg)

**Comment by CelestialReaver** [comment]
I'd recommend running this and then trying again. you never know.

`termux-setup-storage && pkg update -y`
