### ISSUE TITLE
crimera/piko source removed

### ISSUE THREAD

**Issue by xyl-sh** [decipher3114/Revancify#120]
Is there a reason why the crimera/piko Twitter source was removed? As far as I know it hasn't been merged into any of the other sources and is still being actively updated.

**Comment by decipher3114** [comment]
Then you must know that they changed the patches implementation and Revancify isn't compatible with them. Check Revancify v2.

**Comment by decipher3114** [comment]
Crimera patches use the official Revanced CLI which is updated to v5. The patches became obsolete. Is it that hard to understand?

**Comment by kitadai31** [comment]
Crimera themselfs said that crimera patches works with inotia00's cli
https://github.com/crimera/piko/issues/469#issuecomment-2472680507
I believe that setting the cli source to inotia00/revanced-cli may work
