### ISSUE TITLE
Magisk

### ISSUE THREAD

**Issue by TeaqariaWTF** [decipher3114/Revancify#121]
Is it possible to install via magisk?
is it possible to create a zip and flash it via magisk

**Comment by decipher3114** [comment]
This not a magisk module generator, this tool gives you much more freedom over that.

**Comment by TeaqariaWTF** [comment]
> This not a magisk module generator, this tool gives you much more freedom over that.

So how to install on rooted devices, I don't want to use microg

**Comment by decipher3114** [comment]
Revancify mounts app on rooted device and it doesn't require MicroG. This tool is designed for both, rooted and non rooted device.

**Comment by TeaqariaWTF** [comment]
█▀█ █▀▀ █░█ ▄▀█ █▄░█ █▀▀ █ █▀▀ █▄█
           █▀▄ ██▄ ▀▄▀ █▀█ █░▀█ █▄▄ █ █▀░ ░█░


Patching YouTube...
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Merging ./revanced-integrations-v0.51.6.apk
INFO: Skipping music-video-ads, reason: excluded by default
INFO: Skipping codecs-unlock, reason: excluded by default
INFO: Skipping exclusive-audio-playback, reason: excluded by default
INFO: Skipping black-navbar, reason: excluded by default
INFO: Skipping custom-branding-music-revancify, reason: excluded by default
INFO: Skipping custom-branding-music-red, reason: excluded by default
INFO: Skipping compact-header, reason: excluded by default
INFO: Skipping minimized-playback-music, reason: excluded by default
INFO: Skipping hide-get-premium, reason: excluded by default
INFO: Skipping tablet-mode, reason: excluded by default
INFO: Skipping tasteBuilder-remover, reason: excluded by default
INFO: Skipping upgrade-button-remover, reason: excluded by default
INFO: Skipping music-microg-support, reason: excluded by default
INFO: Skipping custom-package-name-music, reason: excluded by default
INFO: Skipping background-play, reason: excluded by default
INFO: Skipping custom-branding-icon-blue, reason: excluded by default
INFO: Skipping custom-branding-icon-revancify, reason: excluded by default
INFO: Skipping materialyou, reason: excluded by default
INFO: Skipping disable-auto-player-popup-panels, reason: excluded by default
INFO: Skipping microg-support, reason: excluded by default
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: general-ads succeeded
INFO: hide-infocard-suggestions succeeded
INFO: video-ads succeeded
INFO: always-autorepeat succeeded
INFO: client-spoof-v2 succeeded
INFO: custom-playback-speed succeeded
INFO: extended succeeded
INFO: hide-button-container succeeded
INFO: hide-my-mix succeeded
INFO: optimize-resource succeeded
INFO: overlay-buttons succeeded
INFO: overlay-buttons-alternative-icon succeeded
INFO: remember-video-quality succeeded
INFO: default-video-speed succeeded
INFO: translations succeeded
INFO: seekbar-tapping succeeded
INFO: swipe-controls succeeded
INFO: amoled succeeded
INFO: disable-auto-captions succeeded
INFO: hide-autoplay-button succeeded
INFO: custom-branding-icon-red succeeded
INFO: custom-branding-name succeeded
INFO: hide-captions-button succeeded
INFO: hide-cast-button succeeded
INFO: hide-pip-notification succeeded
INFO: minimized-playback succeeded
INFO: old-quality-layout succeeded
INFO: hide-email-address succeeded
INFO: disable-create-button succeeded
INFO: hide-shorts-button succeeded
INFO: remove-playerbutton-background succeeded
INFO: return-youtube-dislike succeeded
INFO: sponsorblock succeeded
INFO: disable-startup-shorts-player succeeded
INFO: tablet-mini-player succeeded
INFO: hide-watermark succeeded
INFO: enable-wide-searchbar succeeded
INFO: client-spoof succeeded
INFO: hdr-auto-brightness succeeded
INFO: custom-package-name succeeded
INFO: settings succeeded
INFO: custom-video-buffer succeeded
INFO: Compiling resources
WARNING: cutils-trace E 10-18 20:57:44 20241 20241] Error opening trace file: No such file or directory (2)

**Comment by TeaqariaWTF** [comment]
YouTube app never works

**Comment by TeaqariaWTF** [comment]
can you tell me where i went wrong

Video link : https://gofile.io/d/enYGs1

**Comment by decipher3114** [comment]
I suggest you to try building with official sources. If the issue persists, clear termux data and install Revancify again.


There is no dev who have seen or able to reproduce this issue.
So, it makes it harder to explain what actually the problem is..

**Comment by TeaqariaWTF** [comment]
should any changes be made here to change the package name

**Comment by TeaqariaWTF** [comment]
![Screenshot_20221026-214621](https://user-images.githubusercontent.com/90970076/198110611-c7ba5ea9-eae7-4a41-a5e4-35060d22c7dc.png)
should any changes be made here to change the package name

**Comment by TeaqariaWTF** [comment]
I noticed that the application does not work when I activate the custom-package-name option

**Comment by decipher3114** [comment]
I am not responsible to any thing related to this file. Contact the source maintainer.
