### ISSUE TITLE
Crashing when entering patch menu

### ISSUE THREAD

**Issue by fakerli** [decipher3114/Revancify#121]
![Screenshot_2024-11-21-19-18-10-517_com termux](https://github.com/user-attachments/assets/c8547c6d-e56f-40ce-88cb-92cbea67d6a9)

After latest update

**Comment by decipher3114** [comment]
Delete Assets, Exit and Re run

**Comment by fakerli** [comment]
I deleted Termux and the revancify folder. I even deleted Termux and downloaded the latest version from github.

**Comment by zosoleary** [comment]
> I deleted Termux and the revancify folder. I even deleted Termux and downloaded the latest version from github.

Did that fix it for you, because I also tried that and it's doing the same thing

**Comment by fakerli** [comment]
My bad sorry. No, it didn't fix anything.
