### ISSUE TITLE
Original Revanced option not available 

### ISSUE THREAD

**Issue by Gsparsh22** [decipher3114/Revancify#123]
![Screenshot_2024-12-04-18-02-26-64_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/1cd1f1bd-7eda-45f0-8623-6cb1fed02dad)

**Comment by decipher3114** [comment]
https://github.com/decipher3114/Revancify/tree/main?tab=readme-ov-file#revancify-v1-will-be-deprecated-once-revanced-extended-bring-support-for-rvp-patches
