### ISSUE TITLE
App not installing 

### ISSUE THREAD

**Issue by Sidd-Neog** [decipher3114/Revancify#13]
Hi, Revancify is able to patch all files but the process to install is never completed. It gets some error. Screenshots attached below 
![Screenshot_20220904-083643_Termux](https://user-images.githubusercontent.com/102815216/188295370-90372bb5-b006-4d30-be09-6765dc0d924a.png)
![Screenshot_20220904-083635_Termux](https://user-images.githubusercontent.com/102815216/188295372-f5f56d4f-139a-4ad7-9f28-13518b55bfd6.png)

**Comment by decipher3114** [comment]
Bcz your youtube is running in background. Restart device or kill youtube and then try.

**Comment by Sidd-Neog** [comment]
Shall uninstall or disable the YouTube app?

**Comment by smart12312** [comment]
> Bcz your youtube is running in background. Restart device or kill youtube and then try.

It's not working bro, restarted and even force stoped the youtube app.

**Comment by decipher3114** [comment]
Then I can't really tell why it happens. Sorry. One user also got that before you. No reason is known for this error. It generally means that the file is busy in a process and can't be modified while running.

**Comment by Lucky-069** [comment]
I have a better mount script than this that force mounts! It is the mounting script that actually fails to copy as the user may have used a different installer earlier,probably reisxd installer or any other installer so it somehow obstructs the mounting and copying to Revanced folder!

**Comment by decipher3114** [comment]
What is that??

**Comment by Lucky-069** [comment]
Instead of generating the file within Revancify folder and then copying the generated apk to data/adb/revanced, the script simply generates the apk within the Revanced folder directly avoiding the copy fail issue

**Comment by Lucky-069** [comment]
I have been using the script for three weeks and never had issue updating the app

**Comment by decipher3114** [comment]
That will be worse as if the user doesn't have enough permission, the app won't even build and the error won't be as useful as it is now. 
Also, for your knowledge, this problem is fully fixed now bcz I added the new unmounting command and also created a pull request to the devs with the new command.
so, this error will never be shown again.
