### ISSUE TITLE
Error when switching source to ReVanced Extended

### ISSUE THREAD

**Issue by w4tchdoge** [decipher3114/Revancify#131]
The following error flashes very briefly at the bottom of the screen whenever I try to switch the source to ReVanced Extended ([screenshot](https://files.catbox.moe/fgezcy.jpg)):
```bash
jq: error (at <stdin>:5): Cannot iterate over null (null)
```
I understand that Revancify V2 uses the new `.rvp` patch files. As such, I have checked and the latest RVX patch includes an `.rvp` patch file as a release asset.

I have already re-installed Revancify by:
1. Deleting the `revancify` executable in `$PREFIX/bin`
2. Deleting the `Revancify` folder (and the `revancify_data` folder if it exists) in the Termux home directory
3. Downloading the Revancify installer (`curl -sL https://github.com/decipher3114/Revancify/raw/refs/heads/main/install.sh -o revancifyV2_install.sh`)
4. Running the Revancify installer (`bash revancifyV2_install.sh`)

Revancify version string: `v2.4.2`
Termux shell: Zshell
Zshell version string: `zsh 5.9 (aarch64-unknown-linux-android)`

I would appreciate any insight into whether this is user error, an issue with RVX, or an issue with Revancify.

**Comment by decipher3114** [comment]
Try with v2.4.3

**Comment by w4tchdoge** [comment]
I've updated to the latest version—which is 2.4.5 as I'm writing this comment—and both the source switching and the app patching are working as I expected. Thank you for the fix.
