### ISSUE TITLE
[BUG]Anddea not appearing as source in termux

### ISSUE THREAD

**Issue by MegaBigBossMan** [decipher3114/Revancify#133]
**Describe the bug**
Anddea no longer appearing as source in Termux

**To Reproduce**
1. Go to Termux
2. Enter "revancify update" no quotes
3. Enter "revancify" no quotes
4. Check sources (option 3)
5. See error. 

**Screenshots or Recordings**
![Screenshot_20241212_010353_Termux](https://github.com/user-attachments/assets/05aad57b-6ce7-4029-8d81-8fe2a5a38862)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 20 Ultra
 - Android Version: 13
 - Revancify Version: Latest version for Termux as of 12/12/2024.

**Comment by decipher3114** [comment]
1. `revancify update` is not a valid command. Check all arguments with `revancify -h`
2. Anddea's patches aren't compatible with Revancify yet. When the .rvp patches are released as stable, it will be added to Revancify.

**Comment by MegaBigBossMan** [comment]
> 1. `revancify update` is not a valid command. Check all arguments with `revancify -h`
> 
>     2. Anddea's patches aren't compatible with Revancify yet. When the .rvp patches are released as stable, it will be added to Revancify.

Hello, thank you for the reply. Is this something that has happened recently? Prior to this week Anddea patches were compatible with Revancify through Termux. Also, when I run "revancify update" it does check for an update. 

Please advise. Thank you :)

**Comment by decipher3114** [comment]
The Revancify v1 used to work with `.jar` patches. Now it's `.rvp`.

But the Anddea patches are still not released in stable. It will be added when the stable is released.

**Comment by MegaBigBossMan** [comment]
> The Revancify v1 used to work with `.jar` patches. Now it's `.rvp`.
> 
> But the Anddea patches are still not released in stable. It will be added when the stable is released.

Thank you so much Decipher :) I greatly appreciate it and all the work you do.
