### ISSUE TITLE
[BUG] Patched apps get unmounted after a reboot on APatch

### ISSUE THREAD

**Issue by ComradeWave** [decipher3114/Revancify#134]
**Describe the bug**
Apps patched with Revancify get unmounted after a reboot on APatch

**To Reproduce**
1. Patch an app
2. Install/Mount it
3. Reboot
4. Unmounted app 

**Smartphone (please complete the following information):**
 - Device: Xiaomi 11 Lite 5g NE
 - Android Version: 14 (ap2a)
 - Revancify Version: 2.4.5

**Comment by decipher3114** [comment]
The mount works fine for Magisk and KernelSU.
The issue could be specific to APatch or your device.

Only you can debug it.

**Comment by ComradeWave** [comment]
Alright thanks
