### ISSUE TITLE
[QUESTION] How do I select pre-release in Revancify

### ISSUE THREAD

**Issue by ghost** [decipher3114/Revancify#136]
There used to be a setting that I could enable, is it gone now? I can not find it.

**Comment by decipher3114** [comment]
There is no such option anymore.

**Comment by ghost** [comment]
Wow that sucks, this used ti be my favorite patching app. You even managed to ruin the way user edits patch options. Now you have to download the apk first, then select the patches, and after that you can edit patch options. This fucking app sucks. You should just terminate this project for good.

**Comment by decipher3114** [comment]
Better option is you stop using Revancify

**Comment by decipher3114** [comment]
Also, the Workflow will be changed soon. The patches and options will be edited before downloading and patching the apk.

**Comment by ghost** [comment]
Then you can bring back an option to use pre-release too, otherwise this app is worthless.

**Comment by decipher3114** [comment]
Let's keep this app worthless. Pre-release won't be implemented.
