### ISSUE TITLE
App name changed and force closing

### ISSUE THREAD

**Issue by smart12312** [decipher3114/Revancify#14]
I'm on 17.34.36 version of youtube. It got patched but, its crashing upon opening, and also the app name has been changed.
![Screenshot_20220904-113620](https://user-images.githubusercontent.com/48962229/188299914-37e2fe83-6f62-480a-8276-178e0d5b772a.jpg)

**Comment by decipher3114** [comment]
I can't tell anything about this error, because the script never changes the app name. It is the revanced CLI that modifies app.
I can't anything about it. Ask in revanced github page
