### ISSUE TITLE
About CLI rib lib feature 

### ISSUE THREAD

**Issue by Mohammedibrahim15** [decipher3114/Revancify#14]
In the upcoming releases of Rex. It is assumed that developer will use Revanced cli . Could you please use J-hc CLI that supports rip lib feature instead of Revanced cli as inotia did in his cli.
https://github.com/j-hc/revanced-cli/releases/tag/v3.0.1

**Comment by decipher3114** [comment]
It would be better if you get ReX maintainer's consent over this first.

**Comment by Mohammedibrahim15** [comment]
![Screenshot_20230830_162733_com.github.android.jpg](https://github.com/decipher3114/Revancify/assets/130897201/f2cd3aa6-868f-4648-b329-384212fbdedc)

He already added it in rvx builder and i ask him to add also in revancify. Now i am waiting his response 📌

**Comment by decipher3114** [comment]
Revancify supports multiple sources.
He has hardcoded it in the builder and I have no plans to hardcode another argument cause its already hardcoded for RVX.

Riplibs has no major improvement or advantage.
Saving 60 MB in a phone with 128 GB storage is pointless.
