### ISSUE TITLE
Can't install 


### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [decipher3114/Revancify#149]
Checking availability of current mirror: ok
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:3 https://main.termux-mirror.ml stable InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Err:5 https://main.termux-mirror.ml stable Release
  Redirection from https to 'http://ww38.main.termux-mirror.ml/dists/stable/Release' is forbidden
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to dl.bintray.com:443
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

**Comment by jojojojojoj5564656465465** [comment]
I am on samsung phone

**Comment by decipher3114** [comment]
Download Termux from F-Droid. Not from Playstore..
