### ISSUE TITLE
Both Youtube and YT Music crashes

### ISSUE THREAD

**Issue by Tosonny** [decipher3114/Revancify#15]
It worked only once for me ...some days ago right after installing Termux. After an update of Youtube and YT Music it doesn´t work anymore. What ever I try (uninstall and reinstall Youtube and then start revancify) after patching these apps both don´t launch anymore. I have got a failure / crash message and that´s it.

**Comment by CelestialReaver** [comment]
they work. you need to install Vanced_MicroG.apk

![Screenshot_20220911-194842](https://user-images.githubusercontent.com/331055/189554175-15f65240-9ece-4ec4-9ae1-0a3cdb47c1e5.png)
![Screenshot_20220911-194941](https://user-images.githubusercontent.com/331055/189554177-1b4c7d47-f521-4d90-ad11-2723a5c53e78.png)
