### ISSUE TITLE
Youtube unable to fetch link!!

### ISSUE THREAD

**Issue by JuztinPrime** [decipher3114/Revancify#152]
![Screenshot_20221223_183441_com termux](https://user-images.githubusercontent.com/104496559/209321211-0e6e2888-0a94-4797-8800-8ec2b1dae671.jpg)

YouTube fretch link not working, YT music works has

**Comment by well83** [comment]
Same thing. But only for extended.

**Comment by decipher3114** [comment]
Fixed !!
