### ISSUE TITLE
"patch-options" 

### ISSUE THREAD

**Issue by xXRazzRXx** [decipher3114/Revancify#153]
inotia00 patches require `patch-options` to be included, but they are "excluded by default", although they are in the "Option File Editor". Is this why i need to reapply patches after every phone reboot?
![IMG_20221225_191830](https://user-images.githubusercontent.com/121381729/209476236-dfb7561d-d71f-4059-af25-524b6ad7eda6.jpg)
![209473723-f81764ab-2728-43e2-8fa1-4f8567fecdfa](https://user-images.githubusercontent.com/121381729/209476239-5aa6e799-f2aa-4eb0-bcc8-abdfb7e44dfd.png)

**Comment by decipher3114** [comment]
Fixed !!
