### ISSUE TITLE
Question about the difference

### ISSUE THREAD

**Issue by JimZiii** [decipher3114/Revancify#16]
I've noticed that your version doesn't have the video settings option and that it instead sets it to the last used quality on wifi or data separately.

So I'm just wondering what other changes you've made because i originally was under the impression that your script basically just applied their patch without any changes

And also, why the change on the quality settings option?

**Comment by decipher3114** [comment]
Video quality is not changed by my tool. It is the way Revanced developers made it. My tool only download the apk file and revanced components and built and install them. No other modification is done to the app itself.
If you have any other question related to app, ask it in Revanced discussions page.
