### ISSUE TITLE
Can't fetch resources (inotia source, root)

### ISSUE THREAD

**Issue by broli95** [decipher3114/Revancify#164]
Oops! Unable to download completely. │
                        │                                      │
                        │ Retry or change your Network.        │
                        │

I keep getting this message

**Comment by decipher3114** [comment]
There  is no such problem for me. Maybe some problem with your network.
Try using a VPN or change your ISP.

**Comment by broli95** [comment]
I had to reinitialize revancify from scratch but it worked

**Comment by decipher3114** [comment]
Oh, I forgot to tell you, this problem was due to inotia00's changes to the repo. That's why I added a **Delete all** option in **Resources Menu** for such cases, If you face any such problem in future, use that button.

**Comment by broli95** [comment]
> Oh, I forgot to tell you, this problem was due to inotia00's changes to the repo. That's why I added a **Delete all** option in **Resources Menu** for such cases, If you face any such problem in future, use that button.
> 
> ![Screenshot_20230130-141408_Termux](https://user-images.githubusercontent.com/84389932/215429179-a48ede81-e62f-4244-9483-7945de5ff46a.png)
> 

Got it, thanks for the reply!
