### ISSUE TITLE
Can't mount anything

### ISSUE THREAD

**Issue by broli95** [decipher3114/Revancify#165]
Switched to Termux Monet, trying to mount an app but I keep getting this message:

![Screenshot_20230205-132838_Termux~2.png](https://user-images.githubusercontent.com/22918304/216819409-e8dcaef9-246e-41f7-acd9-cc05746f02f7.png)

**Comment by decipher3114** [comment]
I did some changes, please try once again.

**Comment by broli95** [comment]
Still happening unfortunately

**Comment by decipher3114** [comment]
show the output of this cmd `cat Revancify\.mountlog`

**Comment by broli95** [comment]
"cat: Revancify .mountlog: No such file or directory"

**Comment by decipher3114** [comment]
cat ~/Revancify/.mountlog

**Comment by broli95** [comment]
It doesn't do anything after I press enter

**Comment by decipher3114** [comment]
it means, there is no data in mountlog file.

This should not happen at all.
Can you tell what is the last updated time it shows??

**Comment by broli95** [comment]
If you mean when I launch Revancify, it says February 05, 2023 | 19:13

**Comment by decipher3114** [comment]
It is up to date, I am checking on my device please wait.

**Comment by decipher3114** [comment]
![Screenshot_20230205-202944_Termux](https://user-images.githubusercontent.com/84389932/216827055-9a2405e7-bf24-467b-bdad-f38bc240d003.png)
This is the mountlog and it works fine..

**Comment by broli95** [comment]
In the end I had to use a different builder and it worked, closing the issue

**Comment by decipher3114** [comment]
I have figured out the problem, new devices use complex names containing special characters like `~` and `$` that are used in bash for separate purpose, thus to fix this, I need to put the path in the single quotes and hence a user with a newer device is allowing me to debug in his device, so the bug will be fixed soon.
