### ISSUE TITLE
jq error on startup 

### ISSUE THREAD

**Issue by Genmutant** [decipher3114/Revancify#17]
At the end of the startup, after checking for updates, I get the following error message and then a crash to termux:

`jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq`

I didn't have any problems before, just after the current update. A -r didn't fix it.

**Comment by Genmutant** [comment]
I removed all the tools from the data directory, now it seems to work again. I had expected that the reinstall command would fix something like that.

There was a tool in there without a name (-cli-.jar), but I don't know if that was the problem.

**Comment by N2022062** [comment]
same how to fix
