### ISSUE TITLE
YouTube not working 

### ISSUE THREAD

**Issue by Sahidabir** [decipher3114/Revancify#17]
Latest YouTube not working ... it's crash

**Comment by decipher3114** [comment]
Root or non-root??

**Comment by giejay** [comment]
I have the same issue, non-root. It closes immediately on my Pixel 6

**Comment by CelestialReaver** [comment]
it works. you need to install Vanced_MicroG.apk

![Screenshot_20220911-194842](https://user-images.githubusercontent.com/331055/189554175-15f65240-9ece-4ec4-9ae1-0a3cdb47c1e5.png)
![Screenshot_20220911-194941](https://user-images.githubusercontent.com/331055/189554177-1b4c7d47-f521-4d90-ad11-2723a5c53e78.png)

**Comment by giejay** [comment]
Thanks! That did the trick
