### ISSUE TITLE
Rip--lib feature

### ISSUE THREAD

**Issue by Mohammed1520** [decipher3114/Revancify#177]
Inotia00 has released recent cli with rip lib feature . will this feature be applied in revancify?

**Comment by decipher3114** [comment]
Obviously yes, wait for 2 days, I working on a bigger, may be the biggest change in Revancify...

Don't tell anyone LOL

**Comment by decipher3114** [comment]
Added in this https://github.com/decipher3114/Revancify/commit/a8208e9c7f8b92e31648fd2b7c11c100e086e94b
