### ISSUE TITLE
Unable to download from apkmirror

### ISSUE THREAD

**Issue by jordanyoong1** [decipher3114/Revancify#179]
![Screenshot_2023-03-18-22-49-08-27_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/40160073/226114295-fe9c9046-d0e2-476d-b758-0af3a5045570.jpg)
I get this message whenever I try to patch either Youtube or Youtube Music. I'm using KernelSU.

**Comment by decipher3114** [comment]
it just runs a simple 

su -c dumpsys package "$pkgName"

and I guess dumpsys doesn't have enough permissions to run.
There is no fix from my side. You can try rooting with magisk.
