### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by exvazor** [decipher3114/Revancify#18]
- bash: /data/data/com.termux/files/usr/bin/revancify: Permission denied

**Comment by Lucky-069** [comment]
Mount script failed! I assume or like it says permissions are missing!

**Comment by decipher3114** [comment]
Bro, if you can't understand the problem, don't give your silly solutions plz

**Comment by decipher3114** [comment]
> * bash: /data/data/com.termux/files/usr/bin/revancify: Permission denied

Run troubleshoot command 1 plz

**Comment by keatit71** [comment]
I had the same issue it gives that error from just using the command 'revancify', where as for it to work properly you need to do 'bash revancify'

**Comment by Lucky-069** [comment]
I think the bash file isn't copied into the bin that is why this happened! Do a fresh install. The issue will be fixed
