### ISSUE TITLE
[Help] Support for Termux: Tasker

### ISSUE THREAD

**Issue by IMXEren** [decipher3114/Revancify#183]
Hey, I just tried Revancify in the Termux and the experience was really good.

- Easy to use.
- Does the scraping for the user
- Fast

I'm user of Tasker so I wanted to know if it could be run using the Termux: Tasker plugin in Termux environment. Is there a way for me to write an entire command defining required things (app, patches etc.) & execute it in Termux while evading the Options Menu? This would'd be helpful as I could initiate this in the background using the plugin & Tasker.

Thanks

**Comment by decipher3114** [comment]
Thanks for the appreciation, but revancify is made while keeping in mind about its interactive nature.
Even I would want implement something, I need to do a lot of changes and hence it will be more disastrous than beneficial.

Also, If you patch revanced apps once in a week, then there is no point of automating it at all.

**Comment by IMXEren** [comment]
> Even I would want implement something, I need to do a lot of changes and hence it will be more disastrous than beneficial.

You are correct as it'd be problem for new users but I'm not asking you to implement any additional things rather asking for if I can submit the arguments which would be sufficient for the process.

> Also, If you patch revanced apps once in a week, then there is no point of automating it at all.

It's not about automating the task every day/week/month but capable of doing it whenever I want regardless of requiring me to interact anything.

Anyways, a great project for ReVanced (Extended) especially the scrapping parts.
