### ISSUE TITLE
Revancify install failing

### ISSUE THREAD

**Issue by DatHypnoboi** [decipher3114/Revancify#184]
This is probably a very simple fix, but I cannot figure out what to do. I tried installing Revancify with the command listed, but made a typo. This resulted in the installation failing, but now when I try to run the correct command, I just get the fatal error that "destination path 'Revancify' already exists and is not an empty directory."

**Comment by decipher3114** [comment]
execute this command `~/Revancify/revancify`

This will complete the installation.

**Comment by DatHypnoboi** [comment]
I may be misunderstanding, but I'm pasting the command you gave me in and getting the error: "/data/data/com.termux/files/home/Revancify/revancify: line 102: tput: command not found
Dependencies not installed. Run again with internet connection." 
I'm connected to wi-fi, so I don't know why it's saying I'm not

**Comment by decipher3114** [comment]
This issue is because your network can't ping google.com.
Check it with this command `ping -c 1 google.com`

If it doesn't shows 100% packets received, then the issue is due to your network. Change it or try using Cloudflare or Google DNS.

**Comment by DatHypnoboi** [comment]
Oh, that is the issue, I've run it like 10 times and haven't received the packet every time. Thanks for your help
