### ISSUE TITLE
Suggestion: Adapt to mMicroG now that VancedMicroG is discontinued

### ISSUE THREAD

**Issue by Metallifani666** [decipher3114/Revancify#185]
Hello,

Now that VancedMicroG is no longer in active development, and presumably discontinued, I think it would be great to adapt to mMicroG and make the Revancify script to download it instead. As of now Revancify is still downloading VancedMicroG.

mMicroG releases repo:
https://github.com/inotia00/mMicroG/releases

Thank you.

**Comment by decipher3114** [comment]
mMicrog doesn't have enough "hide icon from launcher" option and also the mMicroG is a temporary replacement. Revanced Team is working on a solution and hope it gets implemented soon. I will update it then.

**Comment by Metallifani666** [comment]
> mMicrog doesn't have "hide icon from launcher" option and also the mMicroG is a temporary replacement. Revanced Team is working on a solution and hope it gets implemented soon. I will update it then.

@inotia00 implemented a patch that hides mMicroG icon from the launcher, can you implement it now?

**Comment by inotia00** [comment]
I am not a maintainer of Revancify
