### ISSUE TITLE
Edit patch option 

### ISSUE THREAD

**Issue by Kiwikip** [decipher3114/Revancify#186]
Edit patch option doesn't work. If I try to acces it, it goes back to the start. Update resources doesn't help. 

https://user-images.githubusercontent.com/130678837/236525033-894794ad-a76d-41e6-a1f9-afc2f998659c.mp4

**Comment by decipher3114** [comment]
You need to delete the previous ones first.

Go to extras menu and delete the patch options file.

**Comment by YouTubeFanBoi** [comment]
I have this same issue, deleting options file didn't fix it.

**Comment by decipher3114** [comment]
@YouTubeFanBoi
The only file this thing depends on is options.json file and delete that should fix this issue.

Would you mind showing me a screenrecording showing the error as well error after deleting the patch options file.

**Comment by YouTubeFanBoi** [comment]
Check the first post, that video shows exactly my issue. The issue stays the same, deleting options file doesn't change anything.

**Comment by decipher3114** [comment]
There was a slight mistake, I fixed it
