### ISSUE TITLE
Suggestion: differentiate output APKs from different sources

### ISSUE THREAD

**Issue by pressRtowin** [decipher3114/Revancify#187]
I.e. right now if I patch the same version of YouTube using both ReVanced and Extended, the second APK would overwrite the first. The source should be indicated in the APK name somehow.

**Comment by decipher3114** [comment]
I see nothing wrong here. It is to prevent huge storage usage. If you want to conserve it, rename it beforehand.

**Comment by decipher3114** [comment]
You are wrong, my friend. The apks of different versions are conserved only in the Revancify folder present in Internal Storage. In termux storage, there will be only 1 version of APK to be kept.

And those are only conserved to faciliate users to fall back to previous in case.

**Comment by decipher3114** [comment]
Add a simple digit or smthng whilst another app is being patched. Is it really that hard ??

**Comment by decipher3114** [comment]
Added in this https://github.com/decipher3114/Revancify/commit/c5be35f11167fd0ec36d1f5a1a7ff0dac7bb5a2c
