### ISSUE TITLE
Allow upgrading base version when app is already installed

### ISSUE THREAD

**Issue by D3SOX** [decipher3114/Revancify#189]
I previously used Revanced Manager and it shows the recommended version. When it increased I downloaded the new APK.
I currently have 18.15.40 patched via revancify installed. I updated the resources but if I want to patch it again now it just asks me if I want to use 18.15.40.

As seen the new recommended version is 18.16.39
![Screenshot_20230508-115034_Termux.png](https://user-images.githubusercontent.com/24937357/236793503-2182be50-2f03-4f86-81ad-fea9e021ac97.png)

If I select No it just goes back to the main menu.
How can I use a new base YT version now? I'd like to use the inbuilt APKMirror scraper and not manually download the APK and use the from APK option.
Am I missing something?

**Comment by D3SOX** [comment]
Updated via Aurora Store and now I get this.

![Screenshot_20230508-124616_Termux.png](https://user-images.githubusercontent.com/24937357/236804796-a515b03d-59a5-40b7-92ba-3053422394d6.png)

When I select No again it just refuses to allow me to select a version.

Why is it like that? I'd like to use the version selector that was there the first time I've used it.

**Comment by decipher3114** [comment]
Because Revancify can't enforce a version normally. Suppose you need to install a particular version which is smaller than the currently installed, then only way is to uninstall the app.
And this means the loss of app data.

So, it is totally handled by the PlayStore.

**Comment by D3SOX** [comment]
Yeah I can lookup the recommended version and install it manually but I just want the APKMirror scraper from revancify to do that. I don't want to lose my data. I think that's possible for revancify to do if you lift the restriction.

**Comment by decipher3114** [comment]
@D3SOX 
The latest commit contains the Core Patch Compatiblity (LSPosed Module that allows version downgrade).
So, devices with this module can downgrade to any version.

This patch partially implements this request.
You have to enable "hasCorePatch" in  revancify preferences. When it will show you the list, select any version. But, make sure you always select the higher version and not the lower one.

Still, I will try to make it more usable for other users as well.

**Comment by D3SOX** [comment]
Cool thanks I'm taking a look. I already have CorePatch enabled on my device. Probably should've mentioned it here as a reference.

**Comment by decipher3114** [comment]
https://github.com/decipher3114/Revancify/commit/d53d7f0014c23c134166ae59b51f8a9dc836cd22

Added this feature for non Core Patch users as well. The version list will be partial, showing only higher versions than that.
