### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Lucky-069** [decipher3114/Revancify#19]
Add a folder to decompile apk and give the output and once the app is mounted, give prompt for the user to delete the files within the folder!

**Comment by decipher3114** [comment]
It is already taken care by revanced by the folder revanced-cache and it is always deleted no matter what.

**Comment by Lucky-069** [comment]
Welp I have tried building on phone, and reisxd builder never cleans the folder. That is why I asked

**Comment by decipher3114** [comment]
Mine does always

![image](https://user-images.githubusercontent.com/84389932/189488241-de249ebb-cc36-4a57-801c-30958ea5db88.png)
