### ISSUE TITLE
Bug: multiple major issues after last update

### ISSUE THREAD

**Issue by pressRtowin** [decipher3114/Revancify#194]
Turns out there's more issues than source changing. Attempting to update resources resulted in this error multiple times:

`Resources are successfully downloaded but Apkmirror API is not accessible. So, patches are not successfully synced. Revancify may crash. Change your network.`

When trying to update resources after having changed sources, it seemed to be inconsistent as to which resources it was trying to update (that of the original source's or the newly selected source).

I finally just ended up getting this error: 

`Oops! Unable to download completely. Retry or change your Network.`

and now I can't launch Revancify at all.

(And my network is fine)

**Comment by decipher3114** [comment]
It's all network dependent. There is no change in Fetching resources or whatsoever.

Try with a different network or use VPN.
