### ISSUE TITLE
Problem with official Revanced repo

### ISSUE THREAD

**Issue by someone5678** [decipher3114/Revancify#195]
![Screenshot_20230510-122524_Termux](https://github.com/decipher3114/Revancify/assets/59456192/4105e4cc-c9d8-499a-bfe9-086ca3d45dec)

Turns out, APKMirror API error appeared only when Official Revanced repo is selected.
This message is always appeared on network, VPN.

Other repos like Revanced Extended, RVX does work correctly without any issues.

If I can grab a log for it, please let me know how to do that. Thank you!

**Comment by decipher3114** [comment]
Revanced has added shit load of apps. The `response json` coming back from `apkmirror.com` was too big to be read as `argument json`.

Now, the json is passed via piped argument. So, now there is no such issue.

**Comment by someone5678** [comment]
> Revanced has added shit load of apps. The `response json` coming back from `apkmirror.com` was too big to be read as `argument json`.
> 
> Now, the json is passed via piped argument. So, now there is no such issue.

Thanks!!

**Comment by decipher3114** [comment]
delete the resources and then try.

**Comment by decipher3114** [comment]
https://github.com/decipher3114/Revancify/assets/84389932/bd4d92d9-c3cc-464d-badf-20de5c2116ef

This is the only way I could prove..
