### ISSUE TITLE
Revancify is not installing the apps, shows a "SAVE FILE IN ~/Downloads"

### ISSUE THREAD

**Issue by francisco-lafe** [decipher3114/Revancify#199]
FYI: I'm trying to install YT-Revanced + MicroG

I'm trying to install on a Nokia 7.1, nonroot android

When I select any app to be installed from Termux, it shows this:
![image](https://github.com/decipher3114/Revancify/assets/90066435/bca958fe-de20-4483-b3c3-09c3d5b1918f)

If I touch on EDIT it shows this: 
![image](https://github.com/decipher3114/Revancify/assets/90066435/c8b5470b-0be9-4c12-84ce-0322373c2805)
If I touch on Open Directory, it does this: 
![image](https://github.com/decipher3114/Revancify/assets/90066435/6af7e854-4444-44f1-bf95-fb42badc12d7)
It opens a new Termux and doesn't install anything it does change the directory. 

[patch_log.txt](https://github.com/decipher3114/Revancify/files/11501656/patch_log.txt)
This is the patch log but nothing relevant. 

What should I do? 
I installed Termux from the official github. 
I pressed "N" on any prompt that showed up when running the command: 
`pkg update -y && pkg install git -y && git clone https://github.com/decipher3114/Revancify.git && ./Revancify/revancify`

**Comment by francisco-lafe** [comment]
Here's the device info:
![image](https://github.com/decipher3114/Revancify/assets/90066435/abf26444-fad2-46c0-a9b6-f9ebd66a813f)

Compilation number:
00WW_4_15C_SP18

**Comment by decipher3114** [comment]
When it asked you for the default way to install apk files, you selected termux. Clearly a mistake. Apk files should only be opened with package installer.
Go to Termux App Info and clear all defaults. And select Package installer next time, it will ask.

You can also install apks from Revancify 📁 in Internal Storage. Use your file manager for that.

**Comment by francisco-lafe** [comment]
> When it asked you for the default way to install apk files, you selected termux. Clearly a mistake. Apk files should only be opened with package installer. Go to Termux App Info and clear all defaults. And select Package installer next time, it will ask.
> 
> You can also install apks from Revancify 📁 in Internal Storage. Use your file manager for that.

Ok thanks, that was not mentioned anywhere on the instructions of the README.md file. 
I'll change the default to be the package installer then. 

Bests,

**Comment by decipher3114** [comment]
It is so common. Every app is installed with the Package Installer. You shouldn't have selected it at first.
