### ISSUE TITLE
Revancify deletes the already existing revanced YT built by another builder. 

### ISSUE THREAD

**Issue by Lucky-069** [decipher3114/Revancify#2]
After running this script, even though the mount failed but the Revanced folder in data/adb is empty, so after the reboot yt music and yt revanced which I made using revanced builder is gone! Ideally this shouldn't happen!

**Comment by decipher3114** [comment]
I fixed this, now it won't delete the data/adb/revanced folder.

Also, if you have the folder empty then, your build is not successful. So, you need a Finished out from jdk.

**Comment by Lucky-069** [comment]
The script does have built apk in revanced cache but I assume it fails to copy in revanced folder!

**Comment by decipher3114** [comment]
In revanced cache doesn't mean it is built. If it is not in the revancify folder, and not even in data/adb then it is not built.
If you cloned this repo today, then OK but if yesterday, I suggest you to delete and clone again.

**Comment by Lucky-069** [comment]
I just got the script when you posted about it on reddit!

**Comment by decipher3114** [comment]
Then run the script again. There must be some issue.
