### ISSUE TITLE
Youtube crashes

### ISSUE THREAD

**Issue by Emanuele-1998** [decipher3114/Revancify#200]
Youtube 18.16.37 and microG Services 0.2.27.231613-vtm-noen  crashes after opening

![Screenshot_20230517_232308_microG Services Core](https://github.com/decipher3114/Revancify/assets/67318166/f1b7cb6a-0745-440e-b2fc-6b22ff99570b)

![Screenshot_20230517_233150_Settings](https://github.com/decipher3114/Revancify/assets/67318166/f7c51a28-e2f7-4fba-abd9-f7e16cf4b736)

![Screenshot_20230518_001115_Termux](https://github.com/decipher3114/Revancify/assets/67318166/23c29e94-c7fd-42ec-b526-0ec7f50cc00a)

**Comment by decipher3114** [comment]
Send the patch_log. It would be beneficial. Also, the version you patched, is it supported??

**Comment by Emanuele-1998** [comment]
I solved with remove spoof wifi patch
