### ISSUE TITLE
Patch failing, patchlog not generated 

### ISSUE THREAD

**Issue by moonlightpiu** [decipher3114/Revancify#201]
Hello ,
When i try to patch yt or yt-m using the termux method  ,i get this error :
`com.fasterxml.jackson.databind.exc.MismatchedInputEx │
│  at [Source: (String)""; line: 1, column: 0]         │
│        at com.fasterxml.jackson.databind.exc.Mismatch││        at com.fasterxml.jackson.databind.ObjectMapper│
│        at com.fasterxml.jackson.databind.ObjectMapper││        at com.fasterxml.jackson.databind.ObjectMapper│
│        at com.fasterxml.jackson.databind.ObjectMapper│
│        at app.revanced.utils.Options.deserialize(Opti││        at app.revanced.utils.Options.setOptions(Optio│
│        at app.revanced.utils.Options.setOptions(Optio││        at app.revanced.cli.command.MainCommand.run(Ma││        at picocli.CommandLine.executeUserObject(Comma│
│        at picocli.CommandLine.access$1500(CommandLine│
│        at picocli.CommandLine$RunLast.executeUserObje│
│        at picocli.CommandLine$RunLast.handle(CommandL│
│        at picocli.CommandLine$RunLast.handle(CommandL│
│        at picocli.CommandLine$AbstractParseResultHand│
│        at picocli.CommandLine$RunLast.execute(Command│
│        at picocli.CommandLine.execute(CommandLine.jav│
│        at app.revanced.cli.main.MainKt.main(Main.kt:7│`

The log files are not generated .

**Comment by decipher3114** [comment]
You have entered wrong value in the patch options file. Delete the patch options file and then patch.

**Comment by moonlightpiu** [comment]
Thank you ,it works again.
