### ISSUE TITLE
Install fails for Revanced and Extended on latest YouTube apps

### ISSUE THREAD

**Issue by gbakeman** [decipher3114/Revancify#206]
Device: NOOK Tablet
Software: Phh-Treble Android 9

See also #11

Just like the issue linked above: Revancify will proceed through the entire patch process without throwing any kind of error. It isn't until the copy procedure that everything falls apart:

> umount: Need 1 arg or -a
> cp: bad 'apps/YouTube-18.19.35/base-Revanced.apk': No such file or directory
> chmod: /data/local/tmp/revancify/com.google.android.youtube.apk: No such file or directory
> chcon: /data/local/tmp/revancify/com.google.android.youtube.apk: No such file or directory
> mount: '/data/local/tmp/revancify/com.google.android.youtube.apk'->'/data/app/com.google.android.youtube-I3QOF-gjMOqadPgcEwkifg==/base.apk': No such file or directory
> try '/data/local/tmp/revancify/com.google.android.youtube.apk' type 'ext3' on '/data/app/com.google.android.youtube-I3QOF-gjMOqadPgcEwkifg==/base.apk'

I'm not quite sure how to interpret this, but how is the script getting so far along in the process before it realizes it can't find these critical apk files?

In the last ticket, the directory listing of `~/storage/Revancify` was asked for, but this does not exist:

```
~ $ ls storage/
dcim  downloads  movies  music  pictures  shared
```

However, `~/Revancify` _does_ exist...

```
~ $ ls Revancify/
LICENSE    binaries  fetch_link.sh     fetch_versions.sh  revancify           root_util.sh
README.md  configs   fetch_patches.sh  main.sh            revancify.keystore  sources.json
```

Both times, when I attempted to build for Revanced and Extended, I let the script choose the appropriate version of YouTube apk to patch. I've also attempted clearing out the files downloaded for Revancify and reinstalling it using the command on the README. Any help is appreciated!

[patch_log.txt](https://github.com/decipher3114/Revancify/files/11682139/patch_log.txt)
[install_log.txt](https://github.com/decipher3114/Revancify/files/11682140/install_log.txt)

**Comment by decipher3114** [comment]
This seems to be very unusual issue. The file actually exists, yet it says no such file exists.

**Comment by gbakeman** [comment]
I went ahead and started from a fresh install of Revancify for this test, and also went through and cleared the three options in the Delete Components menu as requested. I then updated the resources once more.

I've started a patch operation for the latest recommended APK of YouTube (18.19.35) The patch operation appeared to complete successfully, then once again fails with an error "Installation Failed !!" Please see attached for the logs.

I have my suspicions that this is just a bad ROM on my device. I'm having issues with the Revanced Manager, too - namely that the modified APK is lost on a device reboot. Something's not being mounted correctly or something like that, seems to indicate the root I have. I'm only able to use a basic superuser root, Magisk can't be installed to my boot partition. I'm willing to write this problem off as that if you want to close the issue here. Thank you for responding!

[patch_log.txt](https://github.com/decipher3114/Revancify/files/11726635/patch_log.txt)
[install_log.txt](https://github.com/decipher3114/Revancify/files/11726638/install_log.txt)

**Comment by decipher3114** [comment]
Yes, this seems some issue with the permissions. You should try other ROMs.
