### ISSUE TITLE
Please use TCP ping instead of ICMP ping to check network connectivity

### ISSUE THREAD

**Issue by WeeAris** [decipher3114/Revancify#208]
Some firewalls and VPNs block ICMP Ping, so the result of checking network connectivity with ICMP ping in these environment is inaccurate.

**Comment by decipher3114** [comment]
Fine, but in some cases it is intentional.

Like with Jio in India, `raw.githubusercontent.com` are blocked. With ping, revancify would be easily able to tell that the network needs to be changed.

**Comment by WeeAris** [comment]
I know ping is useful, I mean it's not always accurate. You also can use curl to check like this:
```curl -sL --head  --request GET raw.githubusercontent.com | grep '200'```

**Comment by PranavPurwar** [comment]
> Fine, but in some cases it is intentional.
> 
> Like with Jio in India, `raw.githubusercontent.com` are blocked. With ping, revancify would be easily able to tell that the network needs to be changed.

Some other ISP's like `ANI Network` in India are blocking the PING requests to `raw.github.com` for some reason. I believe it would be useful to have the script check for connectivity using other methods if the ICMP ping fails.

**Comment by decipher3114** [comment]
@PranavPurwar There is no exact usecase of ping to github raw urls. The thing is fetching from the github requires access to the url.

Thats why the ping check was added to revancify and its only done once with the installation.
