### ISSUE TITLE
Resources are successfully downloaded but Apkmirror API is not accessible. So, patches are not successfully synced. Revancify may crash.

### ISSUE THREAD

**Issue by JuztinPrime** [decipher3114/Revancify#209]
![Screenshot_20230707_002428_com termux](https://github.com/decipher3114/Revancify/assets/104496559/3d228d77-235b-4516-8a23-8b5cf86bda38)
![Screenshot_20230707_002356_com termux](https://github.com/decipher3114/Revancify/assets/104496559/ee63d916-47a8-4c91-b02f-ca69a62abce8)

I have stable connection but it gives an error.

**Comment by decipher3114** [comment]
Do this first **Delete Components -> Resources**

and then, from your file manager, delete the `Revancify/revanced(or inotia00)-patches.json` file.
