### ISSUE TITLE
Why the difference between online,offline apk

### ISSUE THREAD

**Issue by waesd** [decipher3114/Revancify#211]
Thank you all, a simple question, why when I use the online download of the YouTube application, the output will be 140MB , and when I use the previously downloaded YouTube application on the phone, the output will be 79 MB . the first on for all architectures and second one small size is my phone architectures ..

**Comment by decipher3114** [comment]
There is no such difference AFAIK.

The apk with smaller size is because of a feature implemented by inotia00 in his CLI.

There is no such thing with official Revanced.
