### ISSUE TITLE
Always bother "Run again with internet connection." without internet problem

### ISSUE THREAD

**Issue by WeeAris** [decipher3114/Revancify#215]
I'm sure there's nothing wrong with my network except that the ping command doesn't work.  This prevents me from completing the installation.

**Comment by decipher3114** [comment]
I can't fix this. It's on your side. There is no other way to check for internet.

**Comment by WeeAris** [comment]
> I can't fix this. It's on your side. There is no other way to check for internet.
Emmm. Don't rush to give up. I sure this is can be fixed by use ```curl -sL --head  --request GET raw.githubusercontent.com | grep '200'``` instead of ```ping``` command. This command does not need to worry about the ```ping``` command being blocked.

**Comment by decipher3114** [comment]
There are even more ways to check for this. But ping is the fastest of all.
9ms(ping) vs 40ms(nslookup) vs 600ms(this one) vs 1s(wget spider)

**Comment by WeeAris** [comment]
> There are even more ways to check for this. But ping is the fastest of all. 9ms(ping) vs 40ms(nslookup) vs 600ms(this one) vs 1s(wget spider)

The reason why ping is fast is that the icmp protocol is very simple, which means that there is no data verification, and it is easy to be blocked or hijacked.  HTTP is obviously more complicated, but it is a protocol used in real network access scenarios, and its test results are more accurate and more in line with actual network conditions.
**All in all, I think it's more important to be accurate than fast.**

**Comment by PranavPurwar** [comment]
> There are even more ways to check for this. But ping is the fastest of all.
> 9ms(ping) vs 40ms(nslookup) vs 600ms(this one) vs 1s(wget spider)

Maybe use one of these methods only when PING fails? That wouldn't hurt performance on devices that already work. And for others, slow is better than nothing. It's a one-time process anyway

**Comment by WeeAris** [comment]
> > There are even more ways to check for this. But ping is the fastest of all.
> > 9ms(ping) vs 40ms(nslookup) vs 600ms(this one) vs 1s(wget spider)
> 
> Maybe use one of these methods only when PING fails? That wouldn't hurt performance on devices that already work. And for others, slow is better than nothing. It's a one-time process anyway

good idea
