### ISSUE TITLE
App fails to copy in revanced folder! 

### ISSUE THREAD

**Issue by Lucky-069** [decipher3114/Revancify#22]
App fails to copy in revanced folder. 
Even did fresh install multiple times! 
```
Mounting the app
mv: bad 'com.google.android.apps.youtube.music.apk': Operation not permitted
chmod: : No such file or directory
mount: : need -t
Mount failed...
Exiting the script
```

**Comment by Lucky-069** [comment]
The app installs the fresh mod and even creates the patched apk like the apk exists in the Revancify folder but app fails to install

**Comment by decipher3114** [comment]
I know a way, fork my repo, do your specific changes and then test, if it successfull, then I will surely merge that to my code.

**Comment by Lucky-069** [comment]
Okay sure
