### ISSUE TITLE
Build Fail YouTube music 

### ISSUE THREAD

**Issue by mesofranico** [decipher3114/Revancify#23]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/storage/Revancify/fetch.py", line 14, in <module>                          patches_version = (((requests_session.get('https://api.github.com/repos/revanced/revanced-patches/releases/latest')).json())['name']).replace("v","")
KeyError: 'name'                                        grep: youtubemusic_patches.txt: No such file or directory                                                       sed: can't read latest.txt: No such file or directory   sed: can't read latest.txt: No such file or directory
sed: can't read latest.txt: No such file or directory
sed: can't read latest.txt: No such file or directory
Building YouTube Music Revanced...
Error: Invalid or corrupt jarfile ./revanced-cli-.jar
Mounting the app                                        mv: bad 'com.google.android.apps.youtube.music.apk': No such file or directory                                  chmod: : No such file or directory                      mount: : need -t
Mount failed...
Exiting the script

**Comment by mesofranico** [comment]
![Screenshot_20220912-000531_Termux](https://user-images.githubusercontent.com/8009556/189552782-b03311f9-081d-4e93-a403-1f811c07117f.png)

**Comment by CelestialReaver** [comment]
@mesofranico and you ran the following first?

`termux-setup-storage && pkg update -y && pkg install git -y && cd storage && git clone https://github.com/decipher3114/Revancify && cd Revancify && bash revancify.sh && exit`
