### ISSUE TITLE
Patch descriptions sometimes don't fit on screen

### ISSUE THREAD

**Issue by KobeW50** [decipher3114/Revancify#29]
Example screenshot:

![Screenshot_20231002_194257_Termux.jpg](https://github.com/decipher3114/Revancify/assets/84587632/9cf67427-61fa-4ee2-9853-91a3f9a8a8f5)

Solution: Add a line-wrap for the description text, or have scrolling text (if that is even possible in the tui)

**Comment by decipher3114** [comment]
Zoom out the terminal.

This is a limitation of the "dialog" tool.
