### ISSUE TITLE
Add space after ncurses-utils-y

### ISSUE THREAD

**Issue by Lucky-069** [decipher3114/Revancify#3]
In line 57 I assume there must be space after ncurses-utils, I tried fresh installation thrice and the script failed, only after removing the -y argument or adding a space the script worked

**Comment by Lucky-069** [comment]
There's no such package as ncurses-utils-y! Atleast that's the error i get!

**Comment by Lucky-069** [comment]
Also both Twitter and YouTube music have number 2. Please rectify that aswell!

**Comment by Lucky-069** [comment]
![Screenshot_20220827-162608](https://user-images.githubusercontent.com/78787509/187027135-e2936c57-172a-4cf0-a3e6-b91afcf15b82.png)

**Comment by decipher3114** [comment]
Fixed both
