### ISSUE TITLE
New keystore error

### ISSUE THREAD

**Issue by Sam101011** [decipher3114/Revancify#34]
Hello there. Just saw you updated to CLI v4 and proceeded to patch, but the following error happened:

INFO: Loading patches 
INFO: Decoding app manifest 
INFO: Always autorepeat excluded 
INFO: Hide timestamp excluded 
INFO: Hide album cards excluded 
INFO: Hide seekbar excluded 
INFO: Export all activities excluded 
INFO: Remove screen capture restriction excluded 
INFO: Remove screenshot restriction excluded 
INFO: Spoof Wi-Fi connection excluded 
INFO: Predictive back gesture excluded 
INFO: Override certificate pinning excluded 
INFO: Change package name excluded 
INFO: Enable Android debugging excluded 
INFO: Setting patch options 
INFO: Merging integrations 
INFO: Deleting existing resource cache directory 
INFO: Decoding resources 
INFO: Executing patches 
INFO: Alternative thumbnails succeeded 
INFO: Bypass URL redirects succeeded 
INFO: Client spoof succeeded 
INFO: Comments succeeded 
INFO: Copy video url succeeded 
INFO: Custom branding succeeded 
INFO: Custom player overlay opacity succeeded 
INFO: Disable Shorts on startup succeeded 
INFO: Disable auto captions succeeded 
INFO: Disable fine scrubbing gesture succeeded 
INFO: Disable player popup panels succeeded 
INFO: Disable zoom haptics succeeded 
INFO: Enable debugging succeeded 
INFO: Enable tablet layout succeeded 
INFO: External downloads succeeded 
INFO: HDR auto brightness succeeded 
INFO: Hide 'Load more' button succeeded 
INFO: Hide Shorts components succeeded 
INFO: Hide ads succeeded 
INFO: Hide autoplay button succeeded 
INFO: Hide breaking news shelf succeeded 
INFO: Hide captions button succeeded 
INFO: Hide cast button succeeded 
INFO: Hide crowdfunding box succeeded 
INFO: Hide email address succeeded 
INFO: Hide endscreen cards succeeded 
INFO: Hide filter bar succeeded 
INFO: Hide floating microphone button succeeded 
INFO: Hide info cards succeeded 
INFO: Hide layout components succeeded 
INFO: Hide player buttons succeeded 
INFO: Hide video action buttons succeeded 
INFO: Hide watermark succeeded 
INFO: Minimized playback succeeded 
INFO: Navigation buttons succeeded 
INFO: Old video quality menu succeeded 
INFO: Open links externally succeeded 
INFO: Playback speed succeeded 
INFO: Player flyout menu succeeded 
INFO: Premium heading succeeded 
INFO: Remember video quality succeeded 
INFO: Remove player controls background succeeded 
INFO: Return YouTube Dislike succeeded 
INFO: Seekbar tapping succeeded 
INFO: SponsorBlock succeeded 
INFO: Spoof app version succeeded 
INFO: Swipe controls succeeded 
INFO: Tablet mini player succeeded 
INFO: Theme succeeded 
INFO: Vanced MicroG support succeeded 
INFO: Video ads succeeded 
INFO: Wide searchbar succeeded 
INFO: Compiling modified dex files 
INFO: Compiling modified resources 
INFO: Aligning base.apk 
java.lang.IllegalArgumentException: Keystore does not contain alias ReVanced Key
	at app.revanced.library.ApkSigner.readKeyCertificatePair(ApkSigner.kt:91)
	at app.revanced.library.ApkSigner.newApkSignerBuilder(ApkSigner.kt:228)
	at app.revanced.library.ApkUtils.sign(ApkUtils.kt:79)
	at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:246)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:13)

Rooted: false
Arch: arm64-v8a
App: YouTube v18.38.44
CLI: revanced-cli-v4.0.1.jar
Patches: revanced-patches-v2.193.0.jar
Integrations: revanced-integrations-v0.119.1.apk
Patches argument: -i External downloads -i Copy video url -i Disable fine scrubbing gesture -i Seekbar tapping -i Swipe controls -i Hide ads -i Video ads -i Old video quality menu -i Playback speed -i HDR auto brightness -i Remember video quality -i Vanced MicroG support -i Minimized playback -i Disable zoom haptics -i Enable debugging -i Bypass URL redirects -i Open links externally -i Client spoof -i Hide filter bar -i Hide 'Load more' button -i Hide layout components -i Hide breaking news shelf -i Hide endscreen cards -i Hide floating microphone button -i Hide watermark -i Comments -i Hide email address -i Hide Shorts components -i Hide crowdfunding box -i Hide info cards -i Player flyout menu -i Hide captions button -i Hide autoplay button -i Navigation buttons -i Hide video action buttons -i Hide cast button -i Hide player buttons -i Disable auto captions -i Wide searchbar -i Enable tablet layout -i Disable Shorts on startup -i Theme -i Disable player popup panels -i SponsorBlock -i Custom branding -i Premium heading -i Return YouTube Dislike -i Tablet mini player -i Spoof app version -i Alternative thumbnails -i Custom player overlay opacity -i Remove player controls background

**Comment by jhon1282** [comment]
Exact same issue 🤔

**Comment by Sam101011** [comment]
> Exact same issue 🤔 This for Revanced officials patches. For Revanced Extended Patches work fine.

RVX also updated to cli v4. You have to fetch tools to get the newest patches and cli. The previous patches were the last using cli v3 and that's why they're working.

**Comment by jhon1282** [comment]
> > Exact same issue 🤔 This for Revanced officials patches. For Revanced Extended Patches work fine.
> 
> RVX has also been updated to cli v4. You have to fetch tools to get the newest patches and cli. The previous patches were the last using cli v3 and that's why they're working.

I don't understand what you mean.
I updated Revancify, I downloaded the latest resources for both ReVanced_Extended and ReVanced, but it doesn't work for ReVanced official.
[patch_log.txt](https://github.com/decipher3114/Revancify/files/12859209/patch_log.txt)

**Comment by Sam101011** [comment]
Update:the issue has been fixed(thank you decipher!) and thus I'm closing it. 
But beware:when updating previously patched apps, you have to uninstall the old ones first, as it appears the keystore used to sign the apps has been changed. So remember to backup your yt revanced settings!
