### ISSUE TITLE
Can't connect to Github

### ISSUE THREAD

**Issue by yogi701** [decipher3114/Revancify#37]
Revancify can't connect to Github, tried using vpn and disabling AdGuard DNS but it didn't help
![Screenshot_20231026_172512_Termux](https://github.com/decipher3114/Revancify/assets/80465029/a3d2a08b-9588-4142-a1af-e34b0fae272e)

**Comment by LovecraftianGodsKiller** [comment]
I'm getting this same error!

**Comment by anddea** [comment]
@yogi701 @LovecraftianGodsKiller clearing cache and data/storage of Termux might help, it can be because of some old unpurged data from previous downloads/updates. VPN and adblockers shouldn't affect revancify.

**Comment by LovecraftianGodsKiller** [comment]
@anddea I'm getting the error because I use pacman as my package manager. 

I even reinstalled Termux, changed the package manger to pacman, then ran the command and got the same error.

**Comment by yogi701** [comment]
Oh, forgot about the thread, so the fix was what the @anddea suggested. Thanks for the help :)
