### ISSUE TITLE
Not working, asks to wipe storage?

### ISSUE THREAD

**Issue by JimZiii** [decipher3114/Revancify#4]
First time running it i get that the repositories are down and it can't verify metadata integrity.
But if i try running it again it asks me to clear storage but tells me it won't touch storage at the same time, what's the deal?

![Screenshot_20220831-181448_Termux.jpg](https://user-images.githubusercontent.com/7854537/187728542-09ea0c5b-24cd-495c-9f64-01a2df8cf3c0.jpg)

And this is first time running it
![Screenshot_20220831-181406_Termux.jpg](https://user-images.githubusercontent.com/7854537/187728636-67b46b7c-4bee-48b4-895f-7eb0d7b71bb1.jpg)

**Comment by decipher3114** [comment]
Uninstall Termux, You downloaded that from Playstore, Download termux from their github page.
https://github.com/termux/termux-app/releases/tag/v0.118.0
if you know arch of your phone, download specific arch, else download universal apk
