### ISSUE TITLE
Automatically fetch tools when the source is changed

### ISSUE THREAD

**Issue by KobeW50** [decipher3114/Revancify#40]
When you change the source, you still need to manually fetch the latest tools. It would be nice if it automatically fetched the latest tools whenever you change the source. This can be added as an option in the Preferences menu if some users won't want this.

**Comment by decipher3114** [comment]
It does fetch tools only if they aren't present. If tools of that source is present, be it older versions, it doesn't fetch.

It makes source changing faster.
