### ISSUE TITLE
Revanced Is highly unstable 

### ISSUE THREAD

**Issue by MidnightRetro** [decipher3114/Revancify#41]
I use Revancify to patch Revanced and RVX, both with recommended patches and recommended YouTube versions.
While RVX works perfectly, Revanced keeps crashing as soon as I open it.
I really can't figure out what's going on.
Tried using revanced manager with same patches/YouTube version and it worked fine.

**Comment by Hyakkiculti** [comment]
As for my vanced, it keeps getting delay
