### ISSUE TITLE
Cant update revancify

### ISSUE THREAD

**Issue by JimZiii** [decipher3114/Revancify#44]
I can't update revancify, it's telling me to merge and then aborts, I'll attach a screenshot for you.
Something similar happened a week ago or so, i got a whole page of errors and it told me i needed to merge two branches and aborted, but i reinstalled the script and it started working again, but since it's stopped working twice in a week for seemingly similar reasons i thought you might have a better fix than reinstalling it everytime it fails needs to merge something?

![Screenshot_20220916-142152_Termux.jpg](https://user-images.githubusercontent.com/7854537/190642390-be8b2ccd-83fb-4608-b4d7-ef93e2060450.jpg)

**Comment by decipher3114** [comment]
Yes bro, revanced changed their toml file again. so to update you have to do
```rm ~/storage/Revancify/options.toml```

**Comment by JimZiii** [comment]
Ok so both those times were just you changing the script files and it needing a proper update or reinstall to correct it.
Is it possible to change the script to make it possible to handle this like regular updates, just by running revancify, either by force merging or getting asked [Y/N]
Just a thought

**Comment by JimZiii** [comment]
> Yes bro, revanced changed their toml file again. so to update you have to do `rm ~/storage/Revancify/options.toml`

I deleted

> Yes bro, revanced changed their toml file again. so to update you have to do `rm ~/storage/Revancify/options.toml`

I removed it and I'm pretty sure this is what i got last week. Is this fixable without reinstalling or maybe it's just easier to reinstall when this happens
![Screenshot_20220916-151302_Termux](https://user-images.githubusercontent.com/7854537/190648462-2b08f925-581e-489a-a5c9-49af2788365b.jpg)

**Comment by decipher3114** [comment]
trouble shoot command 1

**Comment by decipher3114** [comment]
on the github page

**Comment by decipher3114** [comment]
Revanced changing its usage constantly that is why these errors arises

**Comment by JimZiii** [comment]
Will do, i was just wondering if it was possible to automate it in your script, that's all.
Thnx

**Comment by decipher3114** [comment]
All this is now added in the latest update, the newest update will omit any such possibility in future.
such as auto rebase command in git, so any file will be changed and it won't give any error.
Also
New command revancify -f to force update.
So, please update it this time by using the # rebase command in the yello text or use the troubleshoot command 2.
Please understand this situation

**Comment by JimZiii** [comment]
No problem. One other question that isnt really worth starting a new 'issue' over

Your script downloads the latest youtube version and even double checks if you already have it downloaded, where is this located? Really can't find it anywhere

**Comment by decipher3114** [comment]
that can't be accessed by file manager.
in termux, do `cd storage/Revancify` and then `ls` to list all items, it is there.
it will delete that version, if a new update is available, so, you don't have to think about this.
Also, if your device is not rooted, the built app will be transfered to /storage/emulated/0/Revancify (the Revancify folder in the Internal Storage)
And if the device is rooted, the built app will overwrite the app located in /data/app/revanced and this won't increase the storage.

You can clear storage by deleting apps in Revancify folder in Internal Storage. Apps downloaded anywhere won't be kept and will be deleted once a new version is found
