### ISSUE TITLE
Cannot patch Sync for Reddit on Android 14; cannot figure out how to horizontally scroll the patch log

### ISSUE THREAD

**Issue by szalapski** [decipher3114/Revancify#52]
Installing Sync for Reddit with Revanced Manager, I can't even see any posts as anonymous, getting a 401. This is with Android 14. (On my previous phone, Revanced Manager worked perfectly.)

So I tried Revancify but **I get an error "Spoof Client failed" during patching** that, if my phone is vertical, further details can't be seen off the right, and if my phone is horizontal, scrolls off the top of screen before I can see the beginning of the error. (**Is there any way in Revancify to scroll up or right on the console log?**) Also, when I try to install with Revancify, **nothing happens**, it just returns to the App Selection Menu and Sync does not appear installed in my launcher--I'm guessing because the patch failed but Revancify doesn't realize it?

I was able to install patched Reddit app (the official one) via ReX using Revancify.

Any idea what else I can try to get Sync for Reddit working?
![Screenshot_20240302-063132](https://github.com/decipher3114/Revancify/assets/2723505/68139104-8aa2-4b74-9b06-2eeef1acce37)

**Comment by Lhn94** [comment]
You need to add your own spoof id client inside the Patch Options. Otherwise, the default value is null so it'll fail.
