### ISSUE TITLE
Package Installer Never Opens

### ISSUE THREAD

**Issue by pressRtowin** [decipher3114/Revancify#53]
When trying to install a patched app, the package installer never opens. The apk file is successfully moved to the /revancify directory in internal storage, but then revancify immediately moves onto the next screen as if the app as been installed, without the package installer ever opening and giving me the option to install. All necessary permissions are granted as far as I'm aware.

Android 14 & Termux monet

**Comment by decipher3114** [comment]
Device specific issue. Revancify isn't responsible for this behaviour. It just executes a command to launch the installer, if it doesn't launches then it is termux issue.
