### ISSUE TITLE
ZipException: zip END header not found

### ISSUE THREAD

**Issue by georgikoemdzhiev** [decipher3114/Revancify#54]
Hello,

Today I tried to patch YouTube and I got an error say `ZipException: zip END header not found`. 

I am attaching the patch log file below:
[patch_log.txt](https://github.com/decipher3114/Revancify/files/14470662/patch_log.txt)

**Comment by zosoleary** [comment]
I am also getting this for all patches

**Comment by georgikoemdzhiev** [comment]
Yep, same. I tried with 'X previously Twitter ' and it fails with the same error.

**Comment by Obscure2020** [comment]
Same here. Tried to repatch YouTube and got the same error.

**Comment by ninajika** [comment]
@georgikoemdzhiev @Obscure2020 @zosoleary can you tried my pr i tested and process patching is successfully patching https://github.com/decipher3114/Revancify/pull/56

*Sorry for my bad English :)

**Comment by georgikoemdzhiev** [comment]
@ninajika thanks for making a patch. I tried it, this time I don't get the error but after the patch when I try to install the patched YouTube it says "App not installed as package conflicts with an existing package"

**Comment by ninajika** [comment]
Hmmm, maybe you need remove old patched YouTube and try again or if you still have revanced.keystore from old Revancify copy that and paste in new Revancify Folder then try again to patch

**Comment by georgikoemdzhiev** [comment]
Thanks for the suggestion. I tried installing/patching an older YouTube version and then I patched the latest recommended one and it worked fine!

**Comment by decipher3114** [comment]
Fixed with commit https://github.com/decipher3114/Revancify/commit/097a4e58c94570b5eb241cbcdf49cea5d1090922

**Comment by M3yo** [comment]
I've updated revancify, the error has changed 
[patch_log.txt](https://github.com/decipher3114/Revancify/files/14472973/patch_log.txt)

**Comment by Obscure2020** [comment]
@M3yo That looks like a new error. Should post as new issue, not as a comment on this one.
