### ISSUE TITLE
Internal directory for app is deleted when trying to download certain older APKs

### ISSUE THREAD

**Issue by pressRtowin** [decipher3114/Revancify#55]
As an example, use any source to patch a recent version of reddit (like 2024.08.0). In Termux's /data/data directory, a directory is created for that specific version of reddit, inside which is a base.apk as well as a copy of the recently patched apk.

Now use any source to attempt to patch reddit again, but this time select version 2024.04.0. No warning will be given. The link appears to be scraped successfully, but rather than proceeding to the download, it immediately goes back to the patch menu. The entire directory for the app is also deleted, along with the base.apk, and the patched apk (even though the version numbers don't even match). This also results in loss of functionality, as you no longer will see the "You've already patched this. Do you want to install instead?" screen if you go back to the first source and attempt to re-patch the same version.

**Comment by decipher3114** [comment]
Directory deletion is intentional to prevent overuse of storage.

The download issue is probaby on your side as the app with the same version downloaded perfectly on my side. Try with a different network.
