### ISSUE TITLE
Missing apps in Revanced source

### ISSUE THREAD

**Issue by pressRtowin** [decipher3114/Revancify#61]
In Revanced Manager, as well as listed on [this page](https://revanced.app/patches), there are 62 packages with supported (non-universal) patches. However, Revancify only lists 41 unique apps, even after deleting and redownloading tools.

**Comment by decipher3114** [comment]
Revancify filters out apps that are available for download from [ApkMirror](apkmirror.com).

You can, however, patch all of the available ones by downloading them manually and choosing the `From Storage` option.
