### ISSUE TITLE
031024 - Revancify CLI immediately crashing after launch without error code. 

### ISSUE THREAD

**Issue by omaralwardian** [decipher3114/Revancify#63]
https://github.com/decipher3114/Revancify/assets/70217313/56792de2-e07c-474b-8dcd-b9055900fb03

Appears to go through the splash screen and then crash. Attached to video here.

No context provided for purposes of a log or crash reason.

**Comment by omaralwardian** [comment]
Alternate methods to start the app including the full command line code curl -sL "https://raw.githubusercontent.com/decipher3114/Revancify/main/install.sh" | bash do not change the outcome. Same result. All packages and dependencies are updated in Termux as well.

**Comment by y-ziane** [comment]
I got the same problem

**Comment by y-ziane** [comment]
> I got the same problem

Nevermind I ended up reinstall it
`revancify -r`

**Comment by DEV-110** [comment]
Same problem

**Comment by DEV-110** [comment]
Before crashing it says invalid json text parsed
