### ISSUE TITLE
Can't install YouTube Revanced. App not installed as package appears to be invalid

### ISSUE THREAD

**Issue by tyw7** [decipher3114/Revancify#64]
Patching using Revancify.  The patch went through successfully, but I can't install it.

INFO: Loading patches  INFO: Decoding app manifest  INFO: Enable slide to seek excluded  INFO: Change header excluded  INFO: Remove player controls background excluded  INFO: Setting patch options  INFO: Merging integrations  INFO: Deleting existing temporary files directory  INFO: Decoding resources  INFO: Executing patches  INFO: Alternative thumbnails succeeded  INFO: Always repeat succeeded  INFO: Announcements succeeded  INFO: Bypass URL redirects succeeded  INFO: Change start page succeeded  INFO: Client spoof succeeded  INFO: Comments succeeded  INFO: Copy video URL succeeded  INFO: Custom branding succeeded  INFO: Custom player overlay opacity succeeded  INFO: Disable auto captions succeeded  INFO: Disable fullscreen ambient mode succeeded  INFO: Disable player popup panels succeeded  INFO: Disable precise seeking gesture succeeded  INFO: Disable resuming Shorts on startup succeeded  INFO: Disable rolling number animations succeeded  INFO: Disable suggested video end screen succeeded  INFO: Disable zoom haptics succeeded  INFO: Enable Android debugging succeeded  INFO: Enable debugging succeeded  INFO: Enable tablet layout succeeded  INFO: Export all activities succeeded  INFO: External downloads succeeded  INFO: GmsCore support succeeded  INFO: HDR auto brightness succeeded  INFO: Hide 'Load more' button succeeded  INFO: Hide Shorts components succeeded  INFO: Hide ads succeeded  INFO: Hide album cards succeeded  INFO: Hide autoplay button succeeded  INFO: Hide breaking news shelf succeeded  INFO: Hide captions button succeeded  INFO: Hide cast button succeeded  INFO: Hide crowdfunding box succeeded  INFO: Hide endscreen cards succeeded  INFO: Hide filter bar succeeded  INFO: Hide floating microphone button succeeded  INFO: Hide info cards succeeded  INFO: Hide layout components succeeded  INFO: Hide player buttons succeeded  INFO: Hide seekbar succeeded  INFO: Hide timestamp succeeded  INFO: Hide video action buttons succeeded  INFO: Minimized playback succeeded  INFO: Navigation buttons succeeded  INFO: Open links externally succeeded  INFO: Override certificate pinning succeeded  INFO: Playback speed succeeded  INFO: Player flyout menu succeeded  INFO: Predictive back gesture succeeded  INFO: Remember video quality succeeded  INFO: Remove screen capture restriction succeeded  INFO: Remove screenshot restriction succeeded  INFO: Remove tracking query parameter succeeded  INFO: Remove viewer discretion dialog succeeded  INFO: Restore old seekbar thumbnails succeeded  INFO: Restore old video quality menu succeeded  INFO: Return YouTube Dislike succeeded  INFO: Seekbar tapping succeeded  INFO: SponsorBlock succeeded  INFO: Spoof SIM country succeeded  INFO: Spoof Wi-Fi connection succeeded  INFO: Spoof app version succeeded  INFO: Spoof device dimensions succeeded  INFO: Swipe controls succeeded  INFO: Tablet mini player succeeded  INFO: Theme succeeded  INFO: Video ads succeeded  INFO: Wide searchbar succeeded  INFO: Change package name succeeded  INFO: Compiling patched dex files  INFO: Compiled classes.dex  INFO: Compiled classes2.dex  INFO: Compiled classes3.dex  INFO: Compiled classes4.dex  INFO: Compiled classes5.dex  INFO: Compiled classes6.dex  INFO: Compiled classes7.dex  INFO: Compiled classes8.dex  INFO: Compiling modified resources  INFO: Aligning APK  INFO: Signing base-Revanced.apk  INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.04.37/base-Revanced.apk  INFO: Purging temporary files  INFO: Purged resource cache directory     Rooted: false Arch: arm64-v8a App: YouTube v19.04.37 CLI: revanced-cli-v4.4.2.jar Patches: revanced-patches-v4.3.0.jar Integrations: revanced-integrations-v1.4.0.apk Patches argument: -i Video ads -i Hide ads -i Spoof device dimensions -i Always repeat -i Minimized playback -i Remove tracking query parameter -i Announcements -i Bypass URL redirects -i Open links externally -i GmsCore support -i Client spoof -i Disable zoom haptics -i Enable debugging -i HDR auto brightness -i Restore old video quality menu -i Playback speed -i Remember video quality -i Disable precise seeking gesture -i Seekbar tapping -i Remove viewer discretion dialog -i External downloads -i Copy video URL -i Swipe controls -i Restore old seekbar thumbnails -i Disable player popup panels -i Custom branding -i Enable tablet layout -i Wide searchbar -i Tablet mini player -i Hide captions button -i Hide autoplay button -i Hide cast button -i Hide player buttons -i Navigation buttons -i Hide video action buttons -i Custom player overlay opacity -i SponsorBlock -i Alternative thumbnails -i Disable resuming Shorts on startup -i Theme -i Spoof app version -i Change start page -i Hide seekbar -i Comments -i Hide breaking news shelf -i Hide Shorts components -i Disable rolling number animations -i Hide floating microphone button -i Hide endscreen cards -i Hide crowdfunding box -i Disable suggested video end screen -i Disable fullscreen ambient mode -i Hide 'Load more' button -i Hide album cards -i Hide filter bar -i Player flyout menu -i Hide layout components -i Hide timestamp -i Hide info cards -i Disable auto captions -i Return YouTube Dislike -i Change package name -i Override certificate pinning -i Enable Android debugging -i Remove screen capture restriction -i Export all activities -i Predictive back gesture -i Spoof SIM country -i Remove screenshot restriction -i Spoof Wi-Fi connection

**Comment by KobeW50** [comment]
Uninstall your existing YT ReVanced installation

**Comment by tyw7** [comment]
I tried that but still the same.

Regards,

Thu Win

**Comment by selfmusing** [comment]
> Patching using Revancify. The patch went through successfully, but I can't install it.
> 
> INFO: Loading patches INFO: Decoding app manifest INFO: Enable slide to seek excluded INFO: Change header excluded INFO: Remove player controls background excluded INFO: Setting patch options INFO: Merging integrations INFO: Deleting existing temporary files directory INFO: Decoding resources INFO: Executing patches INFO: Alternative thumbnails succeeded INFO: Always repeat succeeded INFO: Announcements succeeded INFO: Bypass URL redirects succeeded INFO: Change start page succeeded INFO: Client spoof succeeded INFO: Comments succeeded INFO: Copy video URL succeeded INFO: Custom branding succeeded INFO: Custom player overlay opacity succeeded INFO: Disable auto captions succeeded INFO: Disable fullscreen ambient mode succeeded INFO: Disable player popup panels succeeded INFO: Disable precise seeking gesture succeeded INFO: Disable resuming Shorts on startup succeeded INFO: Disable rolling number animations succeeded INFO: Disable suggested video end screen succeeded INFO: Disable zoom haptics succeeded INFO: Enable Android debugging succeeded INFO: Enable debugging succeeded INFO: Enable tablet layout succeeded INFO: Export all activities succeeded INFO: External downloads succeeded INFO: GmsCore support succeeded INFO: HDR auto brightness succeeded INFO: Hide 'Load more' button succeeded INFO: Hide Shorts components succeeded INFO: Hide ads succeeded INFO: Hide album cards succeeded INFO: Hide autoplay button succeeded INFO: Hide breaking news shelf succeeded INFO: Hide captions button succeeded INFO: Hide cast button succeeded INFO: Hide crowdfunding box succeeded INFO: Hide endscreen cards succeeded INFO: Hide filter bar succeeded INFO: Hide floating microphone button succeeded INFO: Hide info cards succeeded INFO: Hide layout components succeeded INFO: Hide player buttons succeeded INFO: Hide seekbar succeeded INFO: Hide timestamp succeeded INFO: Hide video action buttons succeeded INFO: Minimized playback succeeded INFO: Navigation buttons succeeded INFO: Open links externally succeeded INFO: Override certificate pinning succeeded INFO: Playback speed succeeded INFO: Player flyout menu succeeded INFO: Predictive back gesture succeeded INFO: Remember video quality succeeded INFO: Remove screen capture restriction succeeded INFO: Remove screenshot restriction succeeded INFO: Remove tracking query parameter succeeded INFO: Remove viewer discretion dialog succeeded INFO: Restore old seekbar thumbnails succeeded INFO: Restore old video quality menu succeeded INFO: Return YouTube Dislike succeeded INFO: Seekbar tapping succeeded INFO: SponsorBlock succeeded INFO: Spoof SIM country succeeded INFO: Spoof Wi-Fi connection succeeded INFO: Spoof app version succeeded INFO: Spoof device dimensions succeeded INFO: Swipe controls succeeded INFO: Tablet mini player succeeded INFO: Theme succeeded INFO: Video ads succeeded INFO: Wide searchbar succeeded INFO: Change package name succeeded INFO: Compiling patched dex files INFO: Compiled classes.dex INFO: Compiled classes2.dex INFO: Compiled classes3.dex INFO: Compiled classes4.dex INFO: Compiled classes5.dex INFO: Compiled classes6.dex INFO: Compiled classes7.dex INFO: Compiled classes8.dex INFO: Compiling modified resources INFO: Aligning APK INFO: Signing base-Revanced.apk INFO: Saved to /data/data/com.termux/files/home/revancify-data/apps/YouTube-19.04.37/base-Revanced.apk INFO: Purging temporary files INFO: Purged resource cache directory Rooted: false Arch: arm64-v8a App: YouTube v19.04.37 CLI: revanced-cli-v4.4.2.jar Patches: revanced-patches-v4.3.0.jar Integrations: revanced-integrations-v1.4.0.apk Patches argument: -i Video ads -i Hide ads -i Spoof device dimensions -i Always repeat -i Minimized playback -i Remove tracking query parameter -i Announcements -i Bypass URL redirects -i Open links externally -i GmsCore support -i Client spoof -i Disable zoom haptics -i Enable debugging -i HDR auto brightness -i Restore old video quality menu -i Playback speed -i Remember video quality -i Disable precise seeking gesture -i Seekbar tapping -i Remove viewer discretion dialog -i External downloads -i Copy video URL -i Swipe controls -i Restore old seekbar thumbnails -i Disable player popup panels -i Custom branding -i Enable tablet layout -i Wide searchbar -i Tablet mini player -i Hide captions button -i Hide autoplay button -i Hide cast button -i Hide player buttons -i Navigation buttons -i Hide video action buttons -i Custom player overlay opacity -i SponsorBlock -i Alternative thumbnails -i Disable resuming Shorts on startup -i Theme -i Spoof app version -i Change start page -i Hide seekbar -i Comments -i Hide breaking news shelf -i Hide Shorts components -i Disable rolling number animations -i Hide floating microphone button -i Hide endscreen cards -i Hide crowdfunding box -i Disable suggested video end screen -i Disable fullscreen ambient mode -i Hide 'Load more' button -i Hide album cards -i Hide filter bar -i Player flyout menu -i Hide layout components -i Hide timestamp -i Hide info cards -i Disable auto captions -i Return YouTube Dislike -i Change package name -i Override certificate pinning -i Enable Android debugging -i Remove screen capture restriction -i Export all activities -i Predictive back gesture -i Spoof SIM country -i Remove screenshot restriction -i Spoof Wi-Fi connection

By mistake you've included some unnecessary patches which can cause installation error....


I'll suggest you to use official revanced manager : github.com/revanced/revanced-manager
 , if you want to patch YouTube with official ReVanced patches , else you can just change the patch source to ReX or anddea ( if you want to patch YT with some  extra features )
