### ISSUE TITLE
No Vanced Video Settings

### ISSUE THREAD

**Issue by raychandra7** [decipher3114/Revancify#7]
![Screenshot_2022-09-01-10-47-04-410_com vanced android youtube](https://user-images.githubusercontent.com/112606191/187837058-c8266965-caac-42dd-a909-f54a10bc93fd.jpg)
Can these vanced settings be integrated to revancify ?
There is no settings to save preferred video quality.

**Comment by decipher3114** [comment]
Yes, it saves the last chosen video quality over wifi or mobile data and keep is there unless you change it.
Example: You are watching a video over wifi and selects 1080p, from then all your videos will be shown at 1080p if you are on wifi.
Do the same for mobile data and you set 480p for mobile data, it will saves that and always play 1080p while at wifi and 480p at mobile data.
