### ISSUE TITLE
Can't scrape X/Twitter apk

### ISSUE THREAD

**Issue by JimZiii** [decipher3114/Revancify#7]
When trying to scrape the X/twitter apk it says it's not on apkmirror, i did a quick search on apkmirror and they got the files.
And the files don't show the latest on top, it goes up to version 9.99 and has version 10 at the bottom, but that's not a big deal

**Comment by decipher3114** [comment]
Its a fault by APKMirror.
The appname defined in the result of the API call is "X".
But on website, its called "X (previously Twitter)".

I can fix it tho, but It would be a waste of time. There are no apks available. Only bundles are there.
