### ISSUE TITLE
Error occurred during initialization of VM

### ISSUE THREAD

**Issue by Cloudytfw1** [decipher3114/Revancify#74]
[patch_log.txt](https://github.com/decipher3114/Revancify/files/14837240/patch_log.txt)

https://github.com/decipher3114/Revancify/assets/149498167/b154a7f5-0c6e-46ab-ab56-48a23fc5ceb5

**Comment by decipher3114** [comment]
Run this command

```
pkg remove libandroid-spawn; pkg install libandroid-spawn
```
