### ISSUE TITLE
Request: Please add ReX (YT-Advanced) test build in Sources

### ISSUE THREAD

**Issue by 1node00** [decipher3114/Revancify#8]
This would be really handy to switch between stable and test builds.

Source:

Repository API: https://api.github.com
Patches organization: YT-Advanced
Patches source: testpatches
Integrations organization: YT-Advanced
Integrations source: testinte

**Comment by decipher3114** [comment]
There is no point of adding inconsistent patches source to revancify.

Ask the dev to release patches with pre-release status, so that it can be toogled from preferences, just like revanced does.
