### ISSUE TITLE
Problems with downloading apk from Apkmirror

### ISSUE THREAD

**Issue by Alxon4789** [decipher3114/Revancify#82]
When we want to patch an application (in my case it's YouTube), theoretically the apk downloads, but moments later on the download bar appears a very large number presented in the form of percentages, finally an error pops up.

IN ADVANCE, I restarted the Wi-Fi connection, changed to mobile data, restarted the phone and despite all this, nothing changed. MANUALLY downloading the apk from the site, there are no problems.

<img src="https://github.com/decipher3114/Revancify/assets/143010511/1bdf1d22-2d2a-4cb1-8e80-8c4380546ea2" width=50% height=50%><img src="https://github.com/decipher3114/Revancify/assets/143010511/ee3da0d7-af64-42ec-89a4-d0a3bbf53458" width=50% height=50%>

**Comment by Strange-IPmart** [comment]
Same issue.

**Comment by Git-Boy-Slim** [comment]
I have the same problem. Revancify probably scrapes wrong informations from apkmirror and thinks the app is bigger than it actually is. In fact it downloaded everything correctly, but can't continue to patch the app because of this error. 

Just select the downloaded apk from storage an continue as usual for the moment.

**Comment by inotia00** [comment]
![IgnoreAppSizeCheck jpg](https://github.com/decipher3114/Revancify/assets/108592928/e6a72163-00de-4bc5-9169-ed36539f650f)

As the https://github.com/decipher3114/Revancify/pull/83 was merged, the preference `IgnoreAppSizeCheck` was added to Revancify

You can turn it on in the following path:
```
8 Preferences - IgnoreAppSizeCheck
```

If you turn on preference `IgnoreAppSizeCheck`, Revancify will skip checking the validity of downloaded APKs from APKMirror

This is a temporary workaround for this issue

**Comment by ChrisMiller94** [comment]
![Screenshot_20240725-193722_Termux.png](https://github.com/user-attachments/assets/eb449354-818d-47f3-bcaa-2de91f7717e2)

Same here with the IgnoreAppSizeCheck preference enabled

**Comment by Nick82285** [comment]
Revancify downloading is completely broken for me now. All I get is this error and either the latest commit I don't even have the option to test if ignore size check still works.

**Comment by sanabel-al-firdaws** [comment]
> ![IgnoreAppSizeCheck jpg](https://private-user-images.githubusercontent.com/108592928/334330596-e6a72163-00de-4bc5-9169-ed36539f650f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0MjQyNzMsIm5iZiI6MTcyMzQyMzk3MywicGF0aCI6Ii8xMDg1OTI5MjgvMzM0MzMwNTk2LWU2YTcyMTYzLTAwZGUtNGJjNS05MTY5LWVkMzY1MzlmNjUwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMlQwMDUyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjgwOWE4NmNiODY4ODVkNWU0NWRkYWQwNjdlZTZmOWJiM2JjMGIyZWU4ZmE0NjIwN2FhODFhMmQ2OTkxYzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wTyWcRHrneay8_iQ48njW_anXkoOg1AIJoVgMeRCZDI)
> 
> As the #83 was merged, the `IgnoreAppSizeCheck` setting was added to Revancify
> 
> You can turn it on in the following path:
> 
> ```
> 8 Preferences - IgnoreAppSizeCheck
> ```
> 
> If you turn on the `IgnoreAppSizeCheck` setting, Revancify will skip checking the validity of downloaded APKs from APKMirror
> 
> This is a temporary workaround for this issue

this also fixed the problem that says " apkmirror api can't be accessed"
