### ISSUE TITLE
Script fails after patching everything 

### ISSUE THREAD

**Issue by smart12312** [decipher3114/Revancify#9]
bad 'com.google.android.youtube.apk': Device or resource busy
chmod: : No such file or directory
Mount failed
![Screenshot_20220902-125723](https://user-images.githubusercontent.com/48962229/188082400-1457e46d-b4c0-49d0-8b88-0aec1cd0dcfc.jpg)

**Comment by decipher3114** [comment]
You need to close youtube from recent apps and rebuild then only.
It means the file is currently running

**Comment by smart12312** [comment]
Please reopen the issue, even after force closing the app, same thing is happening

**Comment by decipher3114** [comment]
Bro, I recommend you to restart your device once.
If the issue persists, then it my be issue with your phone. I can't do anything specifically

**Comment by smart12312** [comment]
> Bro, I recommend you to restart your device once. If the issue persists, then it my be issue with your phone. I can't do anything specifically

Restarted and also force stopped the youtube app. It was working on previous version
