### ISSUE TITLE
Issues with pacman bootstrap

### ISSUE THREAD

**Issue by EnderNon** [decipher3114/Revancify#98]
When I ran "Uninstall Patched App" with superuser, my phone just switched off and bugged out. When i tried to boot up I found everything was gone. Thanks a lot 👍

**Comment by decipher3114** [comment]
Well, check the script. There is nothing that delete anything other than the apk file.

**Comment by decipher3114** [comment]
https://github.com/decipher3114/Revancify/blob/cd03e9c1302a1e498a8acc9d98904fa9bbeb2a05/root_util.sh#L9

Here arethe uninstall command. Definitely issue with your phone.

**Comment by decipher3114** [comment]
apt is only required while fetching the dependencies. Switch to apt, fetch deps and then switch back to pacman.
